name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        type: boolean
        default: false

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Update version in project file
      run: |
        sed -i 's/<Version>.*<\/Version>/<Version>${{ github.event.inputs.version }}<\/Version>/' Core/Core.csproj
        sed -i 's/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>${{ github.event.inputs.version }}.0<\/AssemblyVersion>/' Core/Core.csproj
        sed -i 's/<FileVersion>.*<\/FileVersion>/<FileVersion>${{ github.event.inputs.version }}.0<\/FileVersion>/' Core/Core.csproj
        
    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Core/Core.csproj
        git commit -m "chore: bump version to ${{ github.event.inputs.version }}" || exit 0
        git push
        
    - name: Build and test
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
        
    - name: Create packages
      run: |
        dotnet pack Core/Core.csproj --configuration Release --output ./release-packages
        
    - name: Generate release notes
      id: release_notes
      run: |
        echo "## What's Changed" > release_notes.md
        echo "" >> release_notes.md
        echo "### Features" >> release_notes.md
        echo "- Pattern-based document structure recognition" >> release_notes.md
        echo "- Hierarchical chunk organization with parent-child relationships" >> release_notes.md
        echo "- Multiple keyword extraction strategies (Simple and ML.NET)" >> release_notes.md
        echo "- ONNX vectorization framework for semantic embeddings" >> release_notes.md
        echo "- Support for Markdown, numeric, legal, and appendix patterns" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Technical Details" >> release_notes.md
        echo "- Comprehensive test suite with 66 test cases" >> release_notes.md
        echo "- Production-ready with proper error handling and resource management" >> release_notes.md
        echo "- Full .NET 8.0 support with nullable reference types" >> release_notes.md
        echo "- Apache 2.0 licensed" >> release_notes.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
        files: |
          ./release-packages/MarkdownStructureChunker.${{ github.event.inputs.version }}.nupkg
          ./release-packages/MarkdownStructureChunker.${{ github.event.inputs.version }}.snupkg

